apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: mobile-app-build-ios-pipeline
spec:
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build-app
    taskRef: 
      name: mobile-app-build-ios-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image