apiVersion: mf.ibm.com/v1
kind: MFOperator
metadata:
  name: sample-mf
  labels:
    app.kubernetes.io/name: mf-operator
    app.kubernetes.io/instance: mf-instance
    app.kubernetes.io/managed-by: helm
    release: mf-operator-1.0.15
spec:
  ###############################################################################
  # Licensed Materials - Property of IBM.
  # Copyright IBM Corporation 2019. All Rights Reserved.
  # U.S. Government Users Restricted Rights - Use, duplication or disclosure
  # restricted by GSA ADP Schedule Contract with IBM Corp.
  #
  # Contributors:
  # IBM Corporation - initial API and implementation
  ###############################################################################
  
  ###############################################################################
  # Default values for MFOperator
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  ###############################################################################
  
  ###############################################################################
  # Specify architecture (amd64, ppc64le, s390x) and weight to be  used for scheduling as follows :
  #   0 - Do not use
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  # Note: IBM Mobile Foundation Package for Openshift currently supports only amd64 architecture.
  ###############################################################################
  
  ###############################################################################
  ## Global configuration
  ###############################################################################
  global:
    arch:
      amd64: "3 - Most preferred"
      ppc64le: "0 - Do not use"
      s390x: "0 - Do not use"
    image:
      pullPolicy: IfNotPresent
      pullSecret:
    ingress:
      hostname: ""
      secret: ""
      sslPassThrough: false
    https: false
    dbinit:
      enabled: true
      repository: cp.icr.io/cp/mfpf-dbinit
      tag: 2.1.9
      resources:
        requests:
          cpu: 900m
          memory: 900Mi
        limits:
          cpu: 900m
          memory: 900Mi
  ###############################################################################
  ## MFP Server configuration
  ###############################################################################
  mfpserver:
    enabled: true
    repository: cp.icr.io/cp/mfpf-server
    tag: 2.1.9
    consoleSecret: ""
    db:
      type: "DB_TYPE"
      host: "MFPF_SERVER_DB_HOST"
      port: "MFPF_SERVER_DB_PORT"
      name: "MFPF_SERVER_DB_NAME"
      secret: "MFPF_SERVER_DB_SECRET"
      schema: "MFPF_SERVER_DB_SCHEMA"
      ssl: false
      driverPvc: ""
      adminCredentialsSecret: ""
    adminClientSecret: ""
    pushClientSecret: ""
    liveupdateClientSecret: ""
    internalClientSecretDetails:
      adminClientSecretId: mfpadmin
      adminClientSecretPassword: nimdapfm
      pushClientSecretId: push
      pushClientSecretPassword: hsup
    replicas: 3
    autoscaling:
      enabled: false
      min: 1
      max: 10
      targetcpu: 50
    pdb:
      enabled: true
      min: 1
    customConfiguration: ""
    keystoreSecret: ""
    resources:
      requests:
        cpu: 1000m
        memory: 1536Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
  ###############################################################################
  ## MFP Push configuration
  ###############################################################################
  mfppush:
    enabled: true
    repository: cp.icr.io/cp/mfpf-push
    tag: 2.1.9
    replicas: 3
    autoscaling:
      enabled: false
      min: 1
      max: 10
      targetcpu: 50
    pdb:
      enabled: true
      min: 1
    customConfiguration: ""
    keystoreSecret: ""
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
  ###############################################################################
  ## MFP Liveupdate configuration
  ###############################################################################
  mfpliveupdate:
    enabled: false
    repository: cp.icr.io/cp/mfpf-liveupdate
    tag: 2.1.9
    db:
      type: "DB_TYPE"
      host: "MFPF_LIVEUPDATE_DB_HOST"
      port: "MFPF_LIVEUPDATE_DB_PORT"
      name: "MFPF_LIVEUPDATE_DB_NAME"
      secret: "MFPF_LIVEUPDATE_DB_SECRET"
      schema: "MFPF_LIVEUPDATE_DB_SCHEMA"
      ssl: false
      driverPvc: ""
      adminCredentialsSecret: "" 
    replicas: 2
    autoscaling:
      enabled: false
      min: 1
      max: 10
      targetcpu: 50
    pdb:
      enabled: true
      min: 1
    customConfiguration: ""
    keystoreSecret: ""
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
  ###############################################################################
  ## MFP Analytics configuration
  ###############################################################################
  mfpanalytics:
    enabled: false
    repository: cp.icr.io/cp/mfpf-analytics
    tag: 2.1.9
    consoleSecret: ""
    replicas: 2
    autoscaling:
      enabled: false
      min: 1
      max: 10
      targetcpu: 50
    shards: "3"
    replicasPerShard: "1"
    persistence:
      enabled: true
      useDynamicProvisioning: false
      volumeName: "data-stor"
      claimName: ""
      storageClassName: ""
      size: 20Gi
    pdb:
      enabled: true
      min: 1
    customConfiguration: ""
    keystoreSecret: ""
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
 ###############################################################################
  ## MFP Analytics Receiver configuration
 ###############################################################################
  mfpanalytics_recvr:
    enabled: false
    repository: cp.icr.io/cp/mfpf-analytics-recvr
    tag: 2.1.9
    replicas: 1
    autoscaling:
      enabled: false
      min: 1
      max: 10
      targetcpu: 50
    pdb:
      enabled: true
      min: 1
    analyticsRecvrSecret: ""
    customConfiguration: ""
    keystoreSecret: ""
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
  ###############################################################################
  ## MFP Application center configuration
  ###############################################################################
  mfpappcenter:
    enabled: false
    repository: cp.icr.io/cp/mfpf-appcenter
    tag: 2.1.9
    consoleSecret: ""
    db:
      type: "DB_TYPE"
      host: "MFPF_APPCNTR_DB_HOST"
      port: "MFPF_APPCNTR_DB_PORT"
      name: "MFPF_APPCNTR_DB_NAME"
      secret: "MFPF_APPCNTR_DB_SECRET"
      schema: "MFPF_APPCNTR_DB_SCHEMA"
      ssl: false
      driverPvc: ""
      adminCredentialsSecret: ""
    replicas: 1
    autoscaling:
      enabled: false
      min: 1
      max: 10
      targetcpu: 50
    pdb:
      enabled: true
      min: 1
    customConfiguration: ""
    keystoreSecret: ""
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
