apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: application-center-deploy
spec:
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: appcenter-task-steps
    taskRef:
      name: application-center-upload
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
