{{ if .Values.mfpanalytics.enabled -}}
{{ if .Values.mfpanalytics_recvr.enabled -}}
{{- if .Values.mfpanalytics_recvr.pdb.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mfp.analytics-recvr.fullname" . }}
  annotations:
    "helm.sh/hook": "pre-rollback, pre-upgrade, pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app.kubernetes.io/name: {{ template "mfp.analytics-recvr.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    run: {{ template "mfp.analytics-recvr.fullname" . }}
spec:
  minAvailable: {{ .Values.mfpanalytics_recvr.pdb.min }}
  selector:
    matchLabels:
      run: {{ template "mfp.analytics-recvr.fullname" . }}
      app.kubernetes.io/name: {{ template "mfp.analytics-recvr.fullname" . }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: "{{ .Release.Name }}"
      app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{- end -}}
{{- end -}}
{{- end -}}