{{- if .Values.mfpanalytics.enabled}}
{{- if (empty .Values.mfpanalytics.consoleSecret) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: analytics-console-secret
  labels:
    app.kubernetes.io/name: analytics-console-secret
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ quote .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: "{{ .Release.Name }}" 
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}
    run: analytics-console-secret
    jobgroup: mfpsecretjob
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-4"
    "helm.sh/resource-policy": delete-job-if-succeed
spec:
  template:
    metadata:
      name: analytics-console-secret
      labels:
        app.kubernetes.io/name: analytics-console-secret
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ quote .Release.Name }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: "{{ .Release.Name }}" 
        app.kubernetes.io/managed-by: {{ quote .Release.Service }}
        run: analytics-console-secret
        jobgroup: mfpsecretjob
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: mf-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      restartPolicy: OnFailure
      affinity:
        {{- include "nodeAffinity" . | indent 6 }}
      {{/* Prefer horizontal scaling */}}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - analytics-console-secret
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name | quote }}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: ibmcom-opencontent-common-utils-analytics
        image: ibmcom/opencontent-common-utils:1.1.2
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        command:
            - 'bash'
            - '-c'
            - |
              cat <<EOF | kubectl apply -f - 
                apiVersion: v1
                kind: Secret
                metadata:
                  name: mfpanalytics-consolesecret
                type: Opaque
                data:
                  MFPF_ANALYTICS_ADMIN_USER: YWRtaW4=
                  MFPF_ANALYTICS_ADMIN_PASSWORD: YWRtaW4=
              EOF
        resources:
{{ toYaml .Values.global.dbinit.resources | indent 10 }}
{{- end }}
{{- end }}