###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{ if .Values.mfpanalytics.enabled -}}
{{ if .Values.mfpanalytics_recvr.enabled -}}
{{ if .Values.mfpanalytics.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "mfp.analytics-recvr.fullname" . }}-hpa
  labels:
    app.kubernetes.io/name: {{ template "mfp.analytics-recvr.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    run: {{ template "mfp.analytics-recvr.fullname" . }}    
spec:
  maxReplicas: {{ .Values.mfpanalytics_recvr.autoscaling.max }}
  minReplicas: {{ .Values.mfpanalytics_recvr.autoscaling.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "mfp.analytics-recvr.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.mfpanalytics_recvr.autoscaling.targetcpu }}
{{- end }}
{{- end }}
{{- end }}