{{ if .Values.mfpanalytics.enabled -}}
{{ if .Values.mfpanalytics_recvr.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "mfp.analytics-recvr.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "mfp.analytics-recvr.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    run: {{ template "mfp.analytics-recvr.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "mfp.analytics-recvr.fullname" . }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      component: analytics-recvr
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - ports:
    - port: 9080
      protocol: TCP
    - port: 9443
      protocol: TCP
    from:
    - namespaceSelector:
       matchLabels:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ template "mfp.server.fullname" . }}
          release: {{ .Release.Name }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ template "mfp.push.fullname" . }}
          release: {{ .Release.Name }}
  egress:
  - {}
{{- end }}
{{- end }}
