###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
{{ if .Values.mfpserver.enabled -}}
{{ if .Values.mfpliveupdate.enabled -}}
{{ if .Values.mfpliveupdate.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "mfp.liveupdate.fullname" . }}-hpa
  labels:
    app.kubernetes.io/name: {{ template "mfp.liveupdate.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ quote .Release.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}" 
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}    
spec:
  maxReplicas: {{ .Values.mfpliveupdate.autoscaling.max }}
  minReplicas: {{ .Values.mfpliveupdate.autoscaling.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "mfp.liveupdate.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.mfpliveupdate.autoscaling.targetcpu }}
{{- end }}
{{- end }}
{{- end }}