###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
# IBM Corporation - initial API and implementation
###############################################################################
{{ if .Values.mfpserver.enabled -}}
{{ if .Values.mfpliveupdate.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mfp.liveupdate.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "mfp.liveupdate.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ quote .Release.Name }}
    heritage: {{ .Release.Service }}
    component: liveupdate
    app.kubernetes.io/instance: "{{ .Release.Name }}" 
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}
    run: {{ template "mfp.liveupdate.fullname" . }}
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      run: {{ template "mfp.liveupdate.fullname" . }}
  {{- if not .Values.mfpliveupdate.autoscaling.enabled }}
  replicas: {{ .Values.mfpliveupdate.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 25%
     maxSurge: 25%
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/liveupdate-configmap.yaml") . | sha256sum }}
        productName: {{ template "ibm-mobilefoundation.productName" . }}
        productID: {{ template "ibm-mobilefoundation.productID" . }}
        productVersion: {{ template "ibm-mobilefoundation.productVersion" . }}
      labels:
        app.kubernetes.io/name: {{ template "mfp.liveupdate.fullname" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ quote .Release.Name }}
        heritage: {{ .Release.Service }}
        component: liveupdate
        app.kubernetes.io/instance: "{{ .Release.Name }}" 
        app.kubernetes.io/managed-by: {{ quote .Release.Service }}
        run: {{ template "mfp.liveupdate.fullname" . }}
    spec:
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: mf-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      affinity:
        {{- include "nodeAffinity" . | indent 6 }}
      {{/* Prefer horizontal scaling */}}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ template "mfp.liveupdate.fullname" . }}
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name | quote }}
              topologyKey: kubernetes.io/hostname
      volumes:
{{- if .Values.mfpliveupdate.customConfiguration }}
        - name: mfpliveupdate-customconfig
          configMap:
            name: {{ .Values.mfpliveupdate.customConfiguration }}
{{- end }}
{{- if .Values.mfpliveupdate.keystoreSecret }}
        - name: mfpf-certs
          secret:
            secretName: {{ .Values.mfpliveupdate.keystoreSecret }}
{{- end }}
{{- if not (empty .Values.mfpliveupdate.db.driverPvc) }}
        - name: mfpliveupdate-db-driverpvc
          persistentVolumeClaim:
            claimName: {{ .Values.mfpliveupdate.db.driverPvc }}
{{- end }}
      containers:
      - name: {{ template "mfp.liveupdate.fullname" . }}
        readinessProbe:
          httpGet:
            path: /mfpliveupdate/v1/health/status
            port: 9080
          initialDelaySeconds: 50
          periodSeconds: 8
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 50
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        image: "{{ .Values.mfpliveupdate.repository }}:{{ .Values.mfpliveupdate.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        env:
          - name: WLP_LOGGING_CONSOLE_FORMAT
            value: "basic"
          - name: WLP_LOGGING_CONSOLE_LOGLEVEL
            value: "info"
          - name: WLP_LOGGING_CONSOLE_SOURCE
            value: "message,trace,accessLog,ffdc"
{{- if .Values.mfpserver.enabled }}
          - name: MFPF_RUNTIME_SVC_NAME
            value: {{ template "mfp.server.fullname" . }}
{{- if .Values.global.https }}
          - name: MFPF_SERVER_PROTOCOL
            value: "https"
          - name: MFPF_SERVER_PORT
            value: "9443"
{{- else }}
          - name: MFPF_SERVER_PROTOCOL
            value: "http"
          - name: MFPF_SERVER_PORT
            value: "9080"
{{- end }}
{{- end }}
{{- if .Values.mfpanalytics.enabled }}
          - name: MFPF_ANALYTICS_SVC_NAME
            value: {{ template "mfp.analytics.fullname" . }}
{{- if .Values.global.https }}
          - name: MFPF_ANALYTICS_PROTOCOL
            value: "https"
          - name: MFPF_ANALYTICS_PORT
            value: "9443"
{{- else }}
          - name: MFPF_ANALYTICS_PROTOCOL
            value: "http"
          - name: MFPF_ANALYTICS_PORT
            value: "9080"
{{- end }}
{{- end }}
{{- if .Values.mfpliveupdate.keystoreSecret }}
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mfpliveupdate.keystoreSecret }}
                key: KEYSTORE_PASSWORD
          - name: TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mfpliveupdate.keystoreSecret }}
                key: TRUSTSTORE_PASSWORD
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "mfp.liveupdate-configmap.fullname" . }}
        - secretRef:
            name: {{ .Values.mfpliveupdate.db.secret }}
{{- if .Values.mfpliveupdate.db.adminCredentialsSecret }}
        - secretRef:
            name: {{ .Values.mfpliveupdate.db.adminCredentialsSecret }}
{{- end }}
{{- if .Values.mfpserver.liveupdateClientSecret }}
        - secretRef:
            name: {{ .Values.mfpserver.liveupdateClientSecret }} 
{{- else }}
        - secretRef:
            name: mfpliveupdate-clientsecret
{{- end }}
        ports:
          - containerPort: 9080
          - containerPort: 9443
        volumeMounts:  
{{- if .Values.mfpliveupdate.customConfiguration }}
          - name: mfpliveupdate-customconfig
            readOnly: true
            mountPath: /opt/ibm/wlp/usr/servers/mfpf-liveupdate/configDropins/overrides
{{- end }}
{{- if .Values.mfpliveupdate.keystoreSecret }}
          - name: mfpf-certs
            readOnly: true
            mountPath: /opt/ibm/wlp/usr/servers/mfpf-liveupdate/resources/security/keystore.jks
            subPath: keystore.jks
          - name: mfpf-certs
            readOnly: true
            mountPath: /opt/ibm/wlp/usr/servers/mfpf-liveupdate/resources/security/truststore.jks
            subPath: truststore.jks
{{- end }}
{{- if not (empty .Values.mfpliveupdate.db.driverPvc) }}
          - name: mfpliveupdate-db-driverpvc
            mountPath: /opt/ibm/MobileFirst/dbdrivers
{{- end }}
        resources:
{{ toYaml .Values.mfpliveupdate.resources | indent 10 }}
{{- end }}
{{- end }}
