{{ if .Values.mfpserver.enabled -}}
{{ if .Values.mfpliveupdate.enabled -}}
{{- if (empty .Values.mfpserver.liveupdateClientSecret)}}
apiVersion: batch/v1
kind: Job
metadata:
  name: mfpliveupdate-clientsecret
  labels:
    app.kubernetes.io/name: mfpliveupdate-clientsecret
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ quote .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: "{{ .Release.Name }}" 
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}
    run: mfpliveupdate-clientsecret
    jobgroup: mfpclientsecretjob
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": delete-job-if-succeed
spec:
  template:
    metadata:
      name: mfpliveupdate-clientsecret
      labels:
        app.kubernetes.io/name: mfpliveupdate-clientsecret
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ quote .Release.Name }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: "{{ .Release.Name }}" 
        app.kubernetes.io/managed-by: {{ quote .Release.Service }}
        run: mfpliveupdate-clientsecret
        jobgroup: mfpclientsecretjob
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: mf-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      restartPolicy: OnFailure
      affinity:
        {{- include "nodeAffinity" . | indent 6 }}
      {{/* Prefer horizontal scaling */}}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mfpliveupdate-clientsecret
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name | quote }}
              topologyKey: kubernetes.io/hostname
      containers:
      - name: ibmcom-opencontent-common-utils-liveupdate
        image: ibmcom/opencontent-common-utils:1.1.2
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        command:
            - 'bash'
            - '-c'
            - |
              cat <<EOF | kubectl apply -f - 
                apiVersion: v1
                kind: Secret
                metadata:
                  name: mfpliveupdate-clientsecret
                type: Opaque
                data:
                  MFPF_LIVEUPDATE_AUTH_CLIENTID: bGl2ZXVwZGF0ZQ==
                  MFPF_LIVEUPDATE_AUTH_SECRET: ZXRhZHB1ZXZpbA==
              EOF
        resources:
{{ toYaml .Values.global.dbinit.resources | indent 10 }}
{{- end }}
{{- end }}
{{- end }}