{{- if .Values.mfpserver.enabled }}
{{ if .Values.global.dbinit.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "mfp.dbinit.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ template "mfp.dbinit.fullname" . }}-server
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ quote .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server-dbinit
    app.kubernetes.io/instance: "{{ .Release.Name }}" 
    app.kubernetes.io/managed-by: {{ quote .Release.Service }}
    run: {{ template "mfp.dbinit.fullname" . }}-server
    jobgroup: mfpdbinitjob
  annotations:
    "helm.sh/hook": pre-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-2"
    "helm.sh/resource-policy": delete-job-if-succeed
spec:
  template:
    metadata:
      name: {{ template "mfp.dbinit.fullname" . }}-server
      labels:
        app.kubernetes.io/name: {{ template "mfp.dbinit.fullname" . }}-server
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ quote .Release.Name }}
        heritage: {{ .Release.Service }}
        component: server-dbinit
        app.kubernetes.io/instance: "{{ .Release.Name }}" 
        app.kubernetes.io/managed-by: {{ quote .Release.Service }}
        run: {{ template "mfp.dbinit.fullname" . }}-server
        jobgroup: mfpdbinitjob
    spec:
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: mf-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      affinity:
        {{- include "nodeAffinity" . | indent 6 }}
      {{/* Prefer horizontal scaling */}}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ template "mfp.dbinit.fullname" . }}-server
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name | quote }}
              topologyKey: kubernetes.io/hostname
      restartPolicy: OnFailure
      volumes:
{{- if not (empty .Values.mfpserver.db.driverPvc) }}
      - name: mfpserver-db-driverpvc
        persistentVolumeClaim:
          claimName: {{ .Values.mfpserver.db.driverPvc }}
{{- end }}
      containers:
      - name: {{ template "mfp.dbinit.fullname" . }}-admin
        image: "{{ .Values.global.dbinit.repository }}:{{ .Values.global.dbinit.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        command: [ "/bin/bash" ]
        args: [ "-c", "./create-admin-database.sh" ]
        envFrom:
        - secretRef:
            name: {{ .Values.mfpserver.db.secret }}
        env:
        - name: MFPF_CLUSTER_MODE
          value: Cloud 
        - name: MFPF_DB_TYPE
          value: {{ .Values.mfpserver.db.type | lower | quote }}
        - name: MFPF_ADMIN_DB_HOST
          value: {{ .Values.mfpserver.db.host }}
        - name: MFPF_ADMIN_DB_PORT 
          value: "{{ .Values.mfpserver.db.port }}"
        - name: MFPF_ADMIN_DB_NAME
          value: {{ .Values.mfpserver.db.name }}
        - name: MFPF_ADMIN_DB_SCHEMA
          value: {{ .Values.mfpserver.db.schema | upper }}
        - name: SSL_CONNECTION
          value: "{{ .Values.mfpserver.db.ssl }}"
        volumeMounts:
{{- if not (empty .Values.mfpserver.db.driverPvc) }}
          - name: mfpserver-db-driverpvc
            readOnly: true
            mountPath: /opt/ibm/MobileFirst/dbdrivers 
{{- end }}
        resources:
{{ toYaml .Values.global.dbinit.resources | indent 10 }}
      - name: {{ template "mfp.dbinit.fullname" . }}-runtime
        image: "{{ .Values.global.dbinit.repository }}:{{ .Values.global.dbinit.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        command: [ "/bin/bash" ]
        args: [ "-c", "./create-runtime-database.sh" ]
        envFrom:
        - secretRef:
            name: {{ .Values.mfpserver.db.secret }}
        env:
        - name: MFPF_CLUSTER_MODE
          value: Cloud 
        - name: MFPF_DB_TYPE
          value: {{ .Values.mfpserver.db.type | lower | quote }}
        - name: SSL_CONNECTION
          value: "{{ .Values.mfpserver.db.ssl }}"
        - name: MFPF_RUNTIME_DB_HOST
          value: {{ .Values.mfpserver.db.host }}
        - name: MFPF_RUNTIME_DB_PORT
          value: "{{ .Values.mfpserver.db.port }}"
        - name: MFPF_RUNTIME_DB_NAME
          value: {{ .Values.mfpserver.db.name }}
        - name: MFPF_RUNTIME_DB_SCHEMA
          value: {{ .Values.mfpserver.db.schema | upper }}
        volumeMounts:
{{- if not (empty .Values.mfpserver.db.driverPvc) }}
          - name: mfpserver-db-driverpvc
            readOnly: true
            mountPath: /opt/ibm/MobileFirst/dbdrivers 
{{- end }}
        resources:
{{ toYaml .Values.global.dbinit.resources | indent 10 }}
{{- end }}
{{- end }}
